package io.testseer.backend.github;

import io.testseer.backend.analysis.GapReport;
import io.testseer.backend.analysis.ImpactReport;
import io.testseer.backend.query.ConsistencyGapService;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public final class PrCommentFormatter {

    static final String MARKER = "<!-- testseer:pr-analysis -->";

    private PrCommentFormatter() {}

    public record ServiceAnalysis(
            String serviceId,
            ImpactReport impact,
            GapReport gaps,
            List<ConsistencyGapService.ConsistencyGapView> consistencyGaps
    ) {}

    public static String format(int prNumber, String commitSha, List<ServiceAnalysis> analyses, String traceBaseUrl) {
        StringBuilder sb = new StringBuilder();
        sb.append(MARKER).append('\n');
        sb.append("## TestSeer Impact Analysis for PR #").append(prNumber).append('\n');
        sb.append('\n');
        sb.append("**Commit:** `").append(shortSha(commitSha)).append("`\n");
        sb.append('\n');

        if (analyses.isEmpty()) {
            sb.append("_Indexing in progress — no analysis available yet._\n");
        } else {
            for (ServiceAnalysis analysis : analyses) {
                appendServiceSection(sb, analysis);
            }
        }

        sb.append('\n');
        sb.append("_Generated by TestSeer");
        if (traceBaseUrl != null && !traceBaseUrl.isBlank()) {
            sb.append(" — [View full trace](").append(traceBaseUrl.trim()).append(')');
        }
        sb.append("_\n");

        return sb.toString();
    }

    private static void appendServiceSection(StringBuilder sb, ServiceAnalysis analysis) {
        ImpactReport impact = analysis.impact();
        GapReport gaps = analysis.gaps();

        sb.append("### ").append(analysis.serviceId()).append('\n');
        sb.append('\n');

        appendChanged(sb, impact);
        appendAffectedConsumers(sb, impact);
        appendSuggestedTests(sb, impact);
        appendTestGaps(sb, gaps, impact);
        appendConsistencyHints(sb, analysis.consistencyGaps());
        sb.append('\n');
    }

    private static void appendChanged(StringBuilder sb, ImpactReport impact) {
        Set<String> names = impact.changedSymbols().stream()
                .map(sym -> simpleClassName(sym.symbolFqn()))
                .collect(Collectors.toCollection(LinkedHashSet::new));
        if (names.isEmpty()) {
            sb.append("**Changed:** _(none detected)_\n");
        } else {
            sb.append("**Changed:** ").append(String.join(", ", names)).append('\n');
        }
    }

    private static void appendAffectedConsumers(StringBuilder sb, ImpactReport impact) {
        if (impact.affectedConsumers().isEmpty()) {
            sb.append("**Affected services:** _(none)_\n");
            return;
        }
        sb.append("**Affected services:**\n");
        for (ImpactReport.AffectedConsumer consumer : impact.affectedConsumers()) {
            String service = consumer.consumerServiceName() != null
                    ? consumer.consumerServiceName()
                    : consumer.consumerServiceId();
            String call = formatHttpCall(consumer.httpMethod(), consumer.path());
            sb.append("- ").append(service);
            if (!call.isBlank()) {
                sb.append(" (calls ").append(call).append(')');
            }
            sb.append('\n');
        }
    }

    private static void appendSuggestedTests(StringBuilder sb, ImpactReport impact) {
        if (impact.suggestedTestScope().isEmpty()) {
            return;
        }
        sb.append("**Suggested test scope:**\n");
        for (ImpactReport.SuggestedTest test : impact.suggestedTestScope()) {
            sb.append("- ");
            if (!test.exists()) {
                sb.append("⚠️ ");
            }
            sb.append(test.className());
            if (test.exists()) {
                sb.append(" (existing");
                if (test.reason() != null && !test.reason().isBlank()) {
                    sb.append(", ").append(test.reason());
                }
                sb.append(')');
            } else if (test.reason() != null && !test.reason().isBlank()) {
                sb.append(" — ").append(test.reason());
            }
            sb.append('\n');
        }
    }

    private static void appendTestGaps(StringBuilder sb, GapReport gaps, ImpactReport impact) {
        int endpointGaps = (int) gaps.gaps().stream()
                .filter(g -> "ENDPOINT_CONTROLLER".equals(g.kind()))
                .count();
        if (endpointGaps > 0) {
            sb.append("**Test gaps:** ")
                    .append(endpointGaps)
                    .append(endpointGaps == 1 ? " controller lacks" : " controllers lack")
                    .append(" test coverage (ENDPOINT_CONTROLLER gaps)\n");
        }
        if (!impact.missingTestClasses().isEmpty()) {
            sb.append("**Missing test classes:**\n");
            for (String missing : impact.missingTestClasses()) {
                sb.append("- ⚠️ ").append(simpleClassName(missing)).append(" has no test class\n");
            }
        }
    }

    private static void appendConsistencyHints(
            StringBuilder sb,
            List<ConsistencyGapService.ConsistencyGapView> consistencyGaps) {
        if (consistencyGaps == null || consistencyGaps.isEmpty()) {
            return;
        }
        sb.append("**Consistency hints:**\n");
        for (ConsistencyGapService.ConsistencyGapView gap : consistencyGaps) {
            sb.append("- ").append(gap.gapType());
            if (gap.scopeRef() != null && !gap.scopeRef().isBlank()) {
                sb.append(" — ").append(gap.scopeRef());
            }
            if (gap.description() != null && !gap.description().isBlank()) {
                sb.append(" (").append(gap.description()).append(')');
            }
            sb.append('\n');
        }
    }

    private static String formatHttpCall(String method, String path) {
        if (path == null || path.isBlank()) {
            return "";
        }
        if (method != null && !method.isBlank()) {
            return method.toUpperCase() + " " + path;
        }
        return path;
    }

    private static String simpleClassName(String fqn) {
        if (fqn == null || fqn.isBlank()) {
            return "unknown";
        }
        int idx = fqn.lastIndexOf('.');
        return idx >= 0 ? fqn.substring(idx + 1) : fqn;
    }

    private static String shortSha(String commitSha) {
        if (commitSha == null) {
            return "";
        }
        return commitSha.length() > 7 ? commitSha.substring(0, 7) : commitSha;
    }
}
